export const GET_GEOLOCATION_LEVEL1_OPTIONS_SUCCESS = 'GET_GEOLOCATION_LEVEL1_OPTIONS_SUCCESS';
export const GET_GEOLOCATION_LEVEL1_OPTIONS_ERROR = 'GET_GEOLOCATION_LEVEL1_OPTIONS_ERROR';
export const LOADING_REQUEST = 'LOADING_REQUEST';
export const GET_GEOLOCATION_FIELDS_SUCCESS = 'GET_GEOLOCATION_FIELDS_SUCCESS';
export const GET_GEOLOCATION_FIELDS_ERROR = 'GET_GEOLOCATION_FIELDS_ERROR';

