export const GET_OVERALL_CONSOLIDATED_SCANS_SUCCESS = 'DEV_CONFIG_LOCATION_ADD_INPUTLIST';
export const GET_OVERALL_CONSOLIDATED_SCANS_ERROR = 'DEV_CONFIG_LOCATION_ADD_ERROR';
export const LOADING_REQUEST = 'LOADING_REQUEST';