export const DEV_CONFIG_LOCATION_ADD_INPUTLIST = 'DEV_CONFIG_LOCATION_ADD_INPUTLIST';
export const DEV_CONFIG_LOCATION_ADD_DPLIST = 'DEV_CONFIG_LOCATION_ADD_DPLIST';
export const DEV_CONFIG_ROLE_ADD_INPUTLIST = 'DEV_CONFIG_ROLE_ADD_INPUTLIST';
export const DEV_CONFIG_ROLE_ADD_DPLIST = 'DEV_CONFIG_ROLE_ADD_DPLIST';
export const DEV_CONFIG_TNTFLOW_ADD_INPUTLIST = 'DEV_CONFIG_TNTFLOW_ADD_INPUTLIST';
export const DEV_CONFIG_SCANPOINTS_ALLOCATION_ADD_INPUTLIST = 'DEV_CONFIG_SCANPOINTS_ALLOCATION_ADD_INPUTLIST';
export const DEV_CONFIG_ANTI_COUNTERFEIT = 'DEV_CONFIG_ANTI_COUNTERFEIT';